//! Interaction-collection substrate for the TEA host runtime.
//!
//! This module holds the shared UI plumbing used by the [`GuiFeature`] shells
//! in [`crate::bot::gui`] and executed by the [`Host`](crate::bot::gui::rt::Host)
//! event loop: action registration with `Type:timestamp:counter` custom ids,
//! select-menu value extraction, synthetic test events, and the background
//! [`ViewChannel`] collectors that feed Discord interactions into the loop.
//!
//! Pure rendering and state transitions live elsewhere: a feature's `view`
//! maps `&Model` to components, and the pure core in `crate::update`
//! owns the state math. This module never renders and never mutates feature
//! state.
//!
//! [`GuiFeature`]: crate::bot::gui::feature::GuiFeature

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Duration;

use futures::StreamExt;
use poise::serenity_prelude::*;
use tokio::sync::RwLock;
use tokio::sync::mpsc;

use crate::bot::command::Context;

/// Type alias for a thread-safe, shared handle to a Discord message.
type EventMessage<T> = (Option<T>, ViewEvent);
type Registry<T> = Arc<RwLock<ActionRegistry<T>>>;

pub mod pagination;

// ── Actions ───────────────────────────────────────────────────────────────

/// Trait for action types used in interactive views.
pub trait Action: Send + Sync + Clone + std::fmt::Debug {
    /// Returns the UI label associated with this action.
    fn label(&self) -> &'static str;
}

/// Registry for actions that maps unique IDs to action instances.
pub struct ActionRegistry<T> {
    pub actions: HashMap<String, T>,
    prefix: String,
    counter: usize,
}

impl<T: Action> ActionRegistry<T> {
    /// Creates a new, empty registry with a unique prefix based on the type name and timestamp.
    pub fn new() -> Self {
        let type_name = std::any::type_name::<T>();
        let type_name = type_name.rsplit("::").next().unwrap_or(type_name);
        let timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_millis();
        Self {
            actions: HashMap::new(),
            prefix: format!("{type_name}:{timestamp}"),
            counter: 0,
        }
    }

    /// Registers an action and returns a [`RegisteredAction`] for building Discord components.
    pub fn register(&mut self, action: T) -> RegisteredAction {
        let id = format!("{}:{}", self.prefix, self.counter);
        let label = action.label();
        self.counter += 1;
        self.actions.insert(id.clone(), action);
        RegisteredAction { id, label }
    }

    /// Registers an action using given id, and returns a [`RegisteredAction`] for building Discord components.
    ///
    /// If an action is already registered with the same id, the action will be updated, and the
    /// old action is returned.
    pub fn register_with_id(&mut self, id: &str, action: T) -> Option<RegisteredAction> {
        self.actions
            .insert(id.to_string(), action)
            .map(|old| RegisteredAction {
                id: id.to_string(),
                label: old.label(),
            })
    }

    /// Retrieves an action associated with a given `custom_id`.
    pub fn get(&self, id: &str) -> Option<&T> {
        self.actions.get(id)
    }

    /// Clears all registered actions. Called by the host before re-rendering.
    pub fn clear(&mut self) {
        self.actions.clear();
    }
}

impl<T: Action> Default for ActionRegistry<T> {
    fn default() -> Self {
        Self::new()
    }
}

/// A registered action paired with its UI label, used to build Discord components.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RegisteredAction {
    /// The unique custom ID generated by the registry.
    pub id: String,
    /// The display label for the component.
    pub label: &'static str,
}

impl RegisteredAction {
    /// Converts the registered action into a Discord button.
    pub fn as_button(self) -> CreateButton<'static> {
        CreateButton::new(self.id).label(self.label)
    }

    /// Converts the registered action into a Discord select menu.
    pub fn as_select<'a>(self, kind: CreateSelectMenuKind<'a>) -> CreateSelectMenu<'a> {
        CreateSelectMenu::new(self.id, kind)
    }

    /// Converts the registered action into a Discord select menu option.
    pub fn as_select_option(self) -> CreateSelectMenuOption<'static> {
        CreateSelectMenuOption::new(self.label, self.id)
    }
}

// ── View Enums ───────────────────────────────────────────────────────────────

/// Values extracted from a select menu interaction.
#[derive(Debug, Clone)]
pub enum SelectValues {
    String(Vec<String>),
    Channel(Vec<GenericChannelId>),
    Role(Vec<RoleId>),
    User(Vec<UserId>),
}

/// A synthetic button/select event that can be injected into the host loop
/// without a Discord interaction. Reserved for the translation-layer seam
/// (issue #143): no code produces these yet.
#[derive(Debug, Clone)]
pub enum SyntheticEvent {
    Button,
    Select(SelectValues),
}

/// An event that wakes up the host loop.
#[derive(Debug, Clone)]
pub enum ViewEvent {
    /// A component interaction (button click, select menu choice).
    Component(ComponentInteraction),
    /// A modal submission.
    Modal(ModalInteraction),
    /// A message in the channel.
    Message(Message),
    /// A reaction to a listened message.
    Reaction(Reaction),
    /// An async event delivered back to the loop.
    Async,
    /// The view loop timed out.
    Timeout,
    /// A synthetic event injected into the loop directly. Reserved for the
    /// translation-layer seam (issue #143); nothing produces it yet.
    Synthetic(SyntheticEvent),
}

// ── ViewChannel ───────────────────────────────────────────────────────────────

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
/// Configuration for [`ViewChannel`] about what events is collected.
pub struct ViewChannelConfig {
    pub components: bool,
    pub modals: bool,
    pub messages: bool,
    pub reactions: bool,
}

impl Default for ViewChannelConfig {
    fn default() -> Self {
        Self {
            components: true, // What this bot builds most of its responses on
            modals: false,
            messages: false,
            reactions: false,
        }
    }
}

pub struct ViewChannel<T: Action + Send + Sync + 'static> {
    tx: mpsc::UnboundedSender<EventMessage<T>>,
    rx: mpsc::UnboundedReceiver<EventMessage<T>>,
    registry: Registry<T>,
    config: ViewChannelConfig,
}

impl<T: Action + Send + Sync + 'static> ViewChannel<T> {
    pub fn new(config: ViewChannelConfig, registry: Registry<T>) -> Self {
        let (tx, rx) = mpsc::unbounded_channel();
        Self {
            tx,
            rx,
            registry,
            config,
        }
    }

    pub async fn recv(&mut self) -> Option<EventMessage<T>> {
        self.rx.recv().await
    }

    /// Spawns all enabled collectors into background tasks.
    /// Must be called after the first render_view() so msg_id is available.
    pub fn start(
        &self,
        ctx: &Context<'_>,
        msg_id: MessageId,
        author_id: UserId,
        channel_id: GenericChannelId,
        timeout: Duration,
    ) {
        let serenity_ctx = ctx.serenity_context().clone();

        if self.config.components {
            let tx = self.tx.clone();
            let registry = self.registry.clone();
            let sctx = serenity_ctx.clone();
            tokio::spawn(async move {
                let collector = ComponentInteractionCollector::new(&sctx)
                    .author_id(author_id)
                    .message_id(msg_id)
                    .timeout(timeout);
                let mut stream = collector.stream();
                while let Some(interaction) = stream.next().await {
                    let action = registry
                        .read()
                        .await
                        .get(interaction.data.custom_id.as_ref())
                        .cloned();
                    let _ = tx.send((action, ViewEvent::Component(interaction.clone())));
                }
                let _ = tx.send((None, ViewEvent::Timeout));
            });
        }

        if self.config.modals {
            let tx = self.tx.clone();
            let sctx = serenity_ctx.clone();
            let registry = self.registry.clone();
            tokio::spawn(async move {
                let collector = ModalInteractionCollector::new(&sctx)
                    .author_id(author_id)
                    .timeout(timeout);
                let mut stream = collector.stream();
                while let Some(interaction) = stream.next().await {
                    let action = registry
                        .read()
                        .await
                        .get(interaction.data.custom_id.as_ref())
                        .cloned();
                    let _ = tx.send((action, ViewEvent::Modal(interaction.clone())));
                }
            });
        }

        if self.config.messages {
            let tx = self.tx.clone();
            let sctx = serenity_ctx.clone();
            tokio::spawn(async move {
                let collector = MessageCollector::new(&sctx)
                    .author_id(author_id)
                    .channel_id(channel_id)
                    .timeout(timeout);
                let mut stream = collector.stream();
                while let Some(msg) = stream.next().await {
                    let _ = tx.send((None, ViewEvent::Message(msg.clone())));
                }
            });
        }

        if self.config.reactions {
            let tx = self.tx.clone();
            let sctx = serenity_ctx.clone();
            tokio::spawn(async move {
                let collector = ReactionCollector::new(&sctx)
                    .author_id(author_id)
                    .message_id(msg_id)
                    .timeout(timeout);
                let mut stream = collector.stream();
                while let Some(reaction) = stream.next().await {
                    let _ = tx.send((None, ViewEvent::Reaction(reaction.clone())));
                }
            });
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Debug, PartialEq, Clone)]
    enum TestAction {
        First,
        Second,
        #[allow(dead_code)]
        Third,
    }

    impl Action for TestAction {
        fn label(&self) -> &'static str {
            match self {
                TestAction::First => "First",
                TestAction::Second => "Second",
                TestAction::Third => "Third",
            }
        }
    }

    #[test]
    fn action_registry_new() {
        let registry = ActionRegistry::<TestAction>::new();
        assert!(registry.actions.is_empty());
    }

    #[test]
    fn action_registry_register() {
        let mut registry = ActionRegistry::<TestAction>::new();

        let id1 = registry.register(TestAction::First);
        assert!(id1.id.starts_with("TestAction:"));

        let id2 = registry.register(TestAction::Second);
        assert_ne!(id1, id2);
    }

    #[test]
    fn action_registry_resolves_registered_ids_and_rejects_unknown_ids() {
        let mut registry = ActionRegistry::<TestAction>::new();
        let registered = registry.register(TestAction::First);

        assert_eq!(registry.get(&registered.id), Some(&TestAction::First));
        // A custom id from a stale or foreign view never resolves: the host
        // acks the interaction and continues instead of translating a message.
        assert_eq!(registry.get("TestAction:0:999"), None);
    }
}
