//! Discord Components V2 view system.
//!
//! Provides traits and utilities for building interactive UI components using a
//! View-Controller pattern. This system manages the lifecycle of Discord message
//! components (buttons, select menus) and handles user interactions via an event loop.
//!
//! ### Architecture Overview
//! The system is built around three core traits:
//! - [`Action`]: An enum representing all possible user interactions in the view.
//! - [`ViewRender`]: Defines how to translate state into Discord components/embeds.
//! - [`ViewHandler`]: Contains the business logic and state mutations for each action.
//!
//! These are orchestrated by the [`ViewEngine`], which runs an async event loop
//! processing interactions, manual events, and timeouts.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Duration;

use futures::StreamExt;
use log::debug;
use poise::CreateReply;
use poise::ReplyHandle;
use poise::serenity_prelude::*;
use tokio::sync::mpsc;

use crate::bot::commands::Context;
use crate::bot::commands::Error;
use crate::bot::coordinator::Coordinator;

/// Type alias for a thread-safe, shared handle to a Discord message.
pub type SharedReplyHandle<'a> = Arc<tokio::sync::Mutex<Option<ReplyHandle<'a>>>>;

pub mod pagination;

/// Enum representing the type of response content.
///
/// This abstracts over whether a view is rendering a set of components (buttons/selects)
/// or a single embed.
pub enum ResponseKind<'a> {
    /// A set of message components (Buttons, Select Menus).
    Component(Vec<CreateComponent<'a>>),
    /// A single Discord embed.
    Embed(Box<CreateEmbed<'a>>),
}

impl<'a> From<Vec<CreateComponent<'a>>> for ResponseKind<'a> {
    fn from(value: Vec<CreateComponent<'a>>) -> Self {
        ResponseKind::Component(value)
    }
}

impl<'a> From<CreateEmbed<'a>> for ResponseKind<'a> {
    fn from(value: CreateEmbed<'a>) -> Self {
        ResponseKind::Embed(Box::new(value))
    }
}

impl<'a> From<ResponseKind<'a>> for CreateReply<'a> {
    fn from(value: ResponseKind<'a>) -> Self {
        match value {
            ResponseKind::Component(components) => CreateReply::new()
                .flags(MessageFlags::IS_COMPONENTS_V2)
                .components(components),
            ResponseKind::Embed(embed) => CreateReply::new().embed(*embed),
        }
    }
}

/// Trait for action types used in interactive views.
pub trait Action: Send + Sync + Clone {
    /// Returns the UI label associated with this action.
    fn label(&self) -> &'static str;
}

/// Registry for actions that maps unique IDs to action instances.
pub struct ActionRegistry<T> {
    actions: HashMap<String, T>,
    prefix: String,
    counter: usize,
}

impl<T: Action> ActionRegistry<T> {
    /// Creates a new, empty registry with a unique prefix based on the type name and timestamp.
    pub fn new() -> Self {
        let type_name = std::any::type_name::<T>();
        let type_name = type_name.rsplit("::").next().unwrap_or(type_name);
        let timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_millis();
        Self {
            actions: HashMap::new(),
            prefix: format!("{}:{}", type_name, timestamp),
            counter: 0,
        }
    }

    /// Registers an action and returns a [`RegisteredAction`] for building Discord components.
    pub fn register(&mut self, action: T) -> RegisteredAction {
        let id = format!("{}:{}", self.prefix, self.counter);
        let label = action.label();
        self.counter += 1;
        self.actions.insert(id.clone(), action);
        RegisteredAction { id, label }
    }

    /// Retrieves an action associated with a given `custom_id`.
    pub fn get(&self, id: &str) -> Option<&T> {
        self.actions.get(id)
    }

    /// Clears all registered actions. Called before re-rendering.
    pub fn clear(&mut self) {
        self.actions.clear();
    }
}

impl<T: Action> Default for ActionRegistry<T> {
    fn default() -> Self {
        Self::new()
    }
}

/// A registered action paired with its UI label, used to build Discord components.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RegisteredAction {
    /// The unique custom ID generated by the registry.
    pub id: String,
    /// The display label for the component.
    pub label: &'static str,
}

impl RegisteredAction {
    /// Converts the registered action into a Discord button.
    pub fn as_button(self) -> CreateButton<'static> {
        CreateButton::new(self.id).label(self.label)
    }

    /// Converts the registered action into a Discord select menu.
    pub fn as_select<'a>(self, kind: CreateSelectMenuKind<'a>) -> CreateSelectMenu<'a> {
        CreateSelectMenu::new(self.id, kind)
    }

    /// Converts the registered action into a Discord select menu option.
    pub fn as_select_option(self) -> CreateSelectMenuOption<'static> {
        CreateSelectMenuOption::new(self.label, self.id)
    }
}

/// Returned by [`ViewHandler::handle`] to control the engine loop.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ViewCommand {
    /// Re-render the view and update the Discord message.
    Render,
    /// Render once then exit the view loop immediately.
    RenderOnce,
    /// Exit the view loop immediately.
    Exit,
    /// Continue the loop without re-rendering.
    Continue,
    /// The interaction was already responded to (e.g. a modal was opened).
    /// The engine will skip auto-acknowledgement.
    AlreadyResponded,
}

/// An event that wakes up the [`ViewEngine`] loop.
///
/// Replaces the former separate `Trigger` enum — the action and its originating
/// interaction are kept together, eliminating redundancy with [`ViewContext`].
pub enum ViewEvent<T> {
    /// A component interaction (button click, select menu choice).
    Component(T, ComponentInteraction),
    /// A modal submission.
    Modal(T, ModalInteraction),
    /// A message in the channel.
    Message(T, Message),
    /// An async event triggered via [`ViewContext::spawn`].
    Async(T),
    /// The view loop timed out.
    Timeout,
}

impl<T: Clone> ViewEvent<T> {
    /// Returns the action contained in this event, if any.
    /// `Timeout` carries no action.
    pub fn action(&self) -> Option<&T> {
        match self {
            ViewEvent::Component(a, _)
            | ViewEvent::Modal(a, _)
            | ViewEvent::Message(a, _)
            | ViewEvent::Async(a) => Some(a),
            ViewEvent::Timeout => None,
        }
    }
}

/// Trait for sending events to a running [`ViewEngine`].
pub trait ViewSender<T: Action>: Send + Sync {
    fn send(&self, event: ViewEvent<T>);
}

impl<T: Action> ViewSender<T> for mpsc::UnboundedSender<ViewEvent<T>> {
    fn send(&self, event: ViewEvent<T>) {
        let _ = self.send(event);
    }
}

/// Maps child actions of type `C` to parent actions of type `P`.
///
/// Enables the delegation pattern where a child view's interactions are
/// forwarded to the parent's action enum.
pub struct MappedSender<C: Action, P: Action> {
    parent_tx: Arc<dyn ViewSender<P>>,
    wrap: fn(C) -> P,
}

impl<C: Action, P: Action> ViewSender<C> for MappedSender<C, P> {
    fn send(&self, event: ViewEvent<C>) {
        let mapped = match event {
            ViewEvent::Component(c, i) => ViewEvent::Component((self.wrap)(c), i),
            ViewEvent::Modal(c, i) => ViewEvent::Modal((self.wrap)(c), i),
            ViewEvent::Message(c, m) => ViewEvent::Message((self.wrap)(c), m),
            ViewEvent::Async(c) => ViewEvent::Async((self.wrap)(c)),
            ViewEvent::Timeout => ViewEvent::Timeout,
        };
        self.parent_tx.send(mapped);
    }
}

// ── ViewContext ───────────────────────────────────────────────────────────────

/// Passed to [`ViewHandler::handle`] for every non-timeout event.
///
/// Consolidates the Poise context, the event (action + interaction), the async
/// sender, and the shared coordinator into a single parameter.
pub struct ViewContext<'a, T: Action> {
    /// Poise command context.
    pub poise: Context<'a>,
    /// The event that triggered this handler call, including the action and
    /// any associated Discord interaction.
    pub event: ViewEvent<T>,
    /// Sender for dispatching further events back to the engine loop.
    pub tx: Arc<dyn ViewSender<T>>,
    /// Shared coordinator — provides access to the reply handle and nav state.
    pub coordinator: Arc<Coordinator<'a>>,
}

impl<'a, T: Action + 'static> ViewContext<'a, T> {
    /// Returns a reference to the action that triggered this call.
    pub fn action(&self) -> &T {
        self.event
            .action()
            .expect("ViewContext::action called on a Timeout event")
    }

    /// Creates a child context that maps child actions into the parent's action type.
    pub fn map<C: Action + Send + 'static>(
        &self,
        action: C,
        wrap: fn(C) -> T,
    ) -> ViewContext<'a, C> {
        let event = match &self.event {
            ViewEvent::Component(_, i) => ViewEvent::Component(action, i.clone()),
            ViewEvent::Modal(_, i) => ViewEvent::Modal(action, i.clone()),
            ViewEvent::Message(_, m) => ViewEvent::Message(action, m.clone()),
            ViewEvent::Async(_) => ViewEvent::Async(action),
            ViewEvent::Timeout => ViewEvent::Timeout,
        };
        ViewContext {
            poise: self.poise,
            event,
            tx: Arc::new(MappedSender {
                parent_tx: self.tx.clone(),
                wrap,
            }),
            coordinator: self.coordinator.clone(),
        }
    }

    /// Spawns an async task that sends an action back to the engine on completion.
    pub fn spawn<F>(&self, future: F)
    where
        F: std::future::Future<Output = Option<T>> + Send + 'static,
    {
        let tx = self.tx.clone();
        tokio::spawn(async move {
            if let Some(action) = future.await {
                tx.send(ViewEvent::Async(action));
            }
        });
    }
}

/// Defines how a view translates its state into Discord components or an embed.
pub trait ViewRender<T: Action> {
    fn render(&self, registry: &mut ActionRegistry<T>) -> ResponseKind<'_>;

    fn create_reply(&self, registry: &mut ActionRegistry<T>) -> CreateReply<'_> {
        self.render(registry).into()
    }
}

/// Manages state and processes interactions for a view.
#[async_trait::async_trait]
pub trait ViewHandler<T: Action, S: Send + Sync = ()>: Send + Sync {
    /// Handles a non-timeout event.
    ///
    /// Receives the full [`ViewContext`] containing the event, action, sender,
    /// and coordinator. Returns a [`ViewCommand`] controlling the engine loop.
    async fn handle(&mut self, ctx: ViewContext<'_, T>) -> Result<ViewCommand, Error>;

    /// Called when the view loop times out waiting for user input.
    async fn on_timeout(&mut self) -> Result<ViewCommand, Error> {
        Ok(ViewCommand::Exit)
    }
}

/// The engine that drives the entire View lifecycle.
///
/// The `ViewEngine` performs the following cycle:
/// 1. Calls `render()` to display the initial UI.
/// 2. Enters a `tokio::select!` loop waiting for Discord interactions or async events.
/// 3. Matches interactions back to [`Action`] variants using the [`ActionRegistry`].
/// 4. Dispatches the action to the [`ViewHandler`].
/// 5. Reacts to the returned [`ViewCommand`] (Render, Exit, etc.).
pub struct ViewEngine<'a, T, H>
where
    T: Action + Send + Sync + 'static,
    H: ViewHandler<T> + ViewRender<T>,
{
    /// Poise command context.
    pub ctx: Context<'a>,
    /// The combined handler and renderer.
    pub handler: H,
    /// Registry for mapping custom IDs to actions.
    pub registry: ActionRegistry<T>,
    /// Inactivity timeout for the interaction collector.
    pub timeout: Duration,
    /// Whether the engine should auto-acknowledge component interactions.
    pub should_acknowledge: bool,
    /// Shared handle to the active message.
    coordinator: Arc<Coordinator<'a>>,
}

impl<'a, T, H> ViewEngine<'a, T, H>
where
    T: Action + Send + Sync + 'static,
    H: ViewHandler<T> + ViewRender<T>,
{
    pub fn new(
        ctx: Context<'a>,
        handler: H,
        timeout: Duration,
        coordinator: Arc<Coordinator<'a>>,
    ) -> Self {
        Self {
            ctx,
            handler,
            registry: ActionRegistry::new(),
            timeout,
            should_acknowledge: true,
            coordinator,
        }
    }

    /// Sets whether the engine auto-acknowledges component interactions.
    /// Set to `false` when the handler opens a modal and responds manually.
    pub fn acknowledge(mut self, should_acknowledge: bool) -> Self {
        self.should_acknowledge = should_acknowledge;
        self
    }

    /// Re-renders the view, editing the existing message or sending a new one.
    pub async fn render_view(&mut self) -> Result<(), Error> {
        self.registry.clear();
        let reply = self.handler.create_reply(&mut self.registry);

        let existing = {
            let lock = self.coordinator.reply_handle.lock().await;
            lock.as_ref().cloned()
        };

        if let Some(handle) = existing {
            handle.edit(self.ctx, reply).await?;
        } else {
            let handle = self.ctx.send(reply).await?;
            *self.coordinator.reply_handle.lock().await = Some(handle);
        }

        Ok(())
    }

    /// Starts the interactive event loop.
    pub async fn run(&mut self) -> Result<(), Error> {
        self.render_view().await?;

        let (tx, mut rx) = mpsc::unbounded_channel::<ViewEvent<T>>();
        let tx_arc: Arc<dyn ViewSender<T>> = Arc::new(tx.clone());

        let msg_id = {
            let lock = self.coordinator.reply_handle.lock().await;
            lock.as_ref()
                .expect("reply_handle must exist after render_view")
                .message()
                .await?
                .id
        };

        let collector = ComponentInteractionCollector::new(self.ctx.serenity_context())
            .author_id(self.ctx.author().id)
            .message_id(msg_id)
            .timeout(self.timeout);

        let mut stream = collector.stream();

        let poise = self.ctx;
        let coordinator = self.coordinator.clone();

        loop {
            tokio::select! {
                maybe_interaction = stream.next() => {
                    let interaction = match maybe_interaction {
                        Some(i) => i,
                        None => {
                            let _ = tx.send(ViewEvent::Timeout);
                            continue;
                        }
                    };

                    let Some(action) = self.registry.get(&interaction.data.custom_id).cloned() else {
                        if self.should_acknowledge {
                            interaction.create_response(
                                poise.http(),
                                CreateInteractionResponse::Acknowledge,
                            ).await.ok();
                        }
                        continue;
                    };

                    let event = ViewEvent::Component(action, interaction.clone());

                    let view_ctx = ViewContext {
                        poise,
                        event,
                        tx: tx_arc.clone(),
                        coordinator: coordinator.clone(),
                    };

                    let cmd = self.handler.handle(view_ctx).await?;
                    debug!("handle() -> {:?}", cmd);

                    // Prevents interaction failure message after handling
                    if self.should_acknowledge && !matches!(cmd, ViewCommand::AlreadyResponded) {
                        interaction.create_response(
                            poise.http(),
                            CreateInteractionResponse::Acknowledge,
                        ).await.ok();
                    }

                    match cmd {
                        ViewCommand::Render => self.render_view().await?,
                        ViewCommand::Exit   => break,
                        _                   => {}
                    }
                }
                maybe_event = rx.recv() => {
                    let event = match maybe_event {
                        Some(e) => e,
                        None    => break,
                    };

                    let cmd = match event {
                        ViewEvent::Timeout => {
                            self.handler.on_timeout().await?
                        }
                        other => {
                            let view_ctx = ViewContext {
                                poise,
                                event: other,
                                tx: tx_arc.clone(),
                                coordinator: coordinator.clone(),
                            };
                            self.handler.handle(view_ctx).await?
                        }
                    };

                    match cmd {
                        ViewCommand::Render => self.render_view().await?,
                        ViewCommand::RenderOnce => {
                            self.render_view().await?;
                            break
                        },
                        ViewCommand::Exit   => break,
                        _                   => {}
                    }
                }
            }
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Debug, PartialEq, Clone)]
    enum TestAction {
        First,
        Second,
        #[allow(dead_code)]
        Third,
    }

    impl Action for TestAction {
        fn label(&self) -> &'static str {
            match self {
                TestAction::First => "First",
                TestAction::Second => "Second",
                TestAction::Third => "Third",
            }
        }
    }

    #[test]
    fn test_action_registry_new() {
        let registry = ActionRegistry::<TestAction>::new();
        assert!(registry.actions.is_empty());
    }

    #[test]
    fn test_action_registry_register() {
        let mut registry = ActionRegistry::<TestAction>::new();

        let id1 = registry.register(TestAction::First);
        assert!(id1.id.starts_with("TestAction:"));

        let id2 = registry.register(TestAction::Second);
        assert_ne!(id1, id2);
    }
}
