//! Discord Components V2 view system.
//!
//! Provides traits and utilities for building interactive UI components using a
//! View-Controller pattern. This system manages the lifecycle of Discord message
//! components (buttons, select menus) and handles user interactions via an event loop.
//!
//! ### Architecture Overview
//! The system is built around three core traits:
//! - [`Action`]: An enum representing all possible user interactions in the view.
//! - [`ViewRender`]: Defines how to translate state into Discord components/embeds.
//! - [`ViewHandler`]: Contains the business logic and state mutations for each action.
//!
//! These are orchestrated by the [`ViewEngine`], which runs an async event loop
//! processing interactions, manual events, and timeouts.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Duration;

use futures::StreamExt;
use futures::future::BoxFuture;
use log::debug;
use poise::CreateReply;
use poise::ReplyHandle;
use poise::serenity_prelude::*;
use tokio::sync::mpsc;

use crate::bot::commands::Context;
use crate::bot::commands::Error;

/// Type alias for a thread-safe, shared handle to a Discord message.
pub type SharedReplyHandle<'a> = Arc<tokio::sync::Mutex<Option<ReplyHandle<'a>>>>;

pub mod pagination;

/// Enum representing the type of response content.
///
/// This abstracts over whether a view is rendering a set of components (buttons/selects)
/// or a single embed.
pub enum ResponseKind<'a> {
    /// A set of message components (Buttons, Select Menus).
    Component(Vec<CreateComponent<'a>>),
    /// A single Discord embed.
    Embed(Box<CreateEmbed<'a>>),
}

impl<'a> From<Vec<CreateComponent<'a>>> for ResponseKind<'a> {
    fn from(value: Vec<CreateComponent<'a>>) -> Self {
        ResponseKind::Component(value)
    }
}

impl<'a> From<CreateEmbed<'a>> for ResponseKind<'a> {
    fn from(value: CreateEmbed<'a>) -> Self {
        ResponseKind::Embed(Box::new(value))
    }
}

impl<'a> From<ResponseKind<'a>> for CreateReply<'a> {
    fn from(value: ResponseKind<'a>) -> Self {
        match value {
            ResponseKind::Component(components) => CreateReply::new()
                .flags(MessageFlags::IS_COMPONENTS_V2)
                .components(components),
            ResponseKind::Embed(embed) => CreateReply::new().embed(*embed),
        }
    }
}

/// Trait for action types used in interactive views.
///
/// Implement this on an enum to define all possible interactions (clicks, choices)
/// a user can take within a specific view.
pub trait Action: Send + Sync + Clone {
    /// Returns the UI label associated with this action.
    fn label(&self) -> &'static str;
}

/// Registry for actions that maps unique IDs to action instances.
///
/// The `ActionRegistry` tracks which Discord component `custom_id` maps to which
/// business logic [`Action`]. It generates unique prefixes to avoid collisions
/// between different view instances.
pub struct ActionRegistry<T> {
    actions: HashMap<String, T>,
    prefix: String,
    counter: usize,
}

impl<T: Action> ActionRegistry<T> {
    /// Creates a new, empty registry with a unique prefix based on the type name and timestamp.
    pub fn new() -> Self {
        let type_name = std::any::type_name::<T>();
        let type_name = type_name.rsplit("::").next().unwrap_or(type_name);
        let timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_millis();
        let prefix = format!("{}:{}", type_name, timestamp);
        Self {
            actions: HashMap::new(),
            prefix,
            counter: 0,
        }
    }

    /// Registers an action and returns a unique `custom_id` for a Discord component.
    pub fn register(&mut self, action: T) -> RegisteredAction {
        let id = format!("{}:{}", self.prefix, self.counter);
        let label = action.label();
        self.counter += 1;
        self.actions.insert(id.clone(), action);
        RegisteredAction { id, label }
    }

    /// Retrieves an action associated with a given `custom_id`.
    pub fn get(&self, id: &str) -> Option<&T> {
        self.actions.get(id)
    }

    /// Clears all registered actions. Used before re-rendering.
    pub fn clear(&mut self) {
        self.actions.clear();
    }
}

impl<T: Action> Default for ActionRegistry<T> {
    fn default() -> Self {
        Self::new()
    }
}

/// A registered action paired with its UI label.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RegisteredAction {
    /// The unique custom ID generated by the registry.
    pub id: String,
    /// The display label for the component.
    pub label: &'static str,
}

impl RegisteredAction {
    /// Converts the registered action into a Discord button.
    pub fn as_button(self) -> CreateButton<'static> {
        CreateButton::new(self.id).label(self.label)
    }

    /// Converts the registered action into a Discord select menu.
    pub fn as_select<'a>(self, kind: CreateSelectMenuKind<'a>) -> CreateSelectMenu<'a> {
        CreateSelectMenu::new(self.id, kind)
    }

    /// Converts the registered action into a Discord select menu option.
    pub fn as_select_option(self) -> CreateSelectMenuOption<'static> {
        CreateSelectMenuOption::new(self.label, self.id)
    }
}

/// Enum returned by controller callbacks to signal the next action for the view loop.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ViewCommand {
    /// Re-render the view and update the Discord message.
    Render,
    /// Exit the view loop immediately.
    Exit,
    /// Continue the loop without re-rendering the message.
    Continue,
    /// Indicates the interaction was already responded to (e.g., a modal was opened),
    /// so the engine should NOT auto-acknowledge it.
    AlreadyResponded,
}

/// Represents an event that wakes up the [`ViewEngine`] loop.
pub enum ViewEvent<T> {
    /// A component interaction (button click, select menu choice).
    Component(T, ComponentInteraction),
    /// A modal submission interaction.
    Modal(T, ModalInteraction),
    /// A message received in the channel (if the view listens for it).
    Message(T, Message),
    /// An asynchronous event triggered manually (e.g., background data fetch completion).
    Async(T),
    /// The view loop timed out waiting for user input.
    Timeout,
}

/// Detailed information about what triggered a view action.
pub enum Trigger<'a> {
    /// Triggered by a component interaction.
    Component(&'a ComponentInteraction),
    /// Triggered by a modal submission.
    Modal(&'a ModalInteraction),
    /// Triggered by a standard message.
    Message(&'a Message),
    /// Triggered asynchronously via [`ViewContext::spawn`].
    Async,
    /// Triggered by the loop timeout.
    Timeout,
}

/// Trait for sending events to a running [`ViewEngine`].
pub trait ViewSender<T: Action>: Send + Sync {
    /// Sends a [`ViewEvent`] to the engine.
    fn send(&self, event: ViewEvent<T>);
}

impl<T: Action> ViewSender<T> for mpsc::UnboundedSender<ViewEvent<T>> {
    fn send(&self, event: ViewEvent<T>) {
        let _ = self.send(event);
    }
}

/// A sender that maps child view actions of type `C` to parent actions of type `P`.
///
/// This enables the **Delegation Pattern**, where a parent view embeds a child view
/// and wraps its interactions into its own action enum.
pub struct MappedSender<C: Action, P: Action> {
    parent_tx: Arc<dyn ViewSender<P>>,
    wrap: fn(C) -> P,
}

impl<C: Action, P: Action> ViewSender<C> for MappedSender<C, P> {
    fn send(&self, event: ViewEvent<C>) {
        let mapped_event = match event {
            ViewEvent::Component(c, i) => ViewEvent::Component((self.wrap)(c), i),
            ViewEvent::Modal(c, i) => ViewEvent::Modal((self.wrap)(c), i),
            ViewEvent::Message(c, m) => ViewEvent::Message((self.wrap)(c), m),
            ViewEvent::Async(c) => ViewEvent::Async((self.wrap)(c)),
            ViewEvent::Timeout => ViewEvent::Timeout,
        };
        self.parent_tx.send(mapped_event);
    }
}

/// Context passed to [`ViewHandler`] callbacks.
///
/// Provides access to the Poise command context and a channel to trigger
/// new actions asynchronously.
pub struct ViewContext<'a, T> {
    /// The underlying Poise command context.
    pub poise: Context<'a>,
    /// The channel used to send events back to the view loop.
    pub tx: Arc<dyn ViewSender<T>>,
}

impl<'a, T: Action + Send + 'static> ViewContext<'a, T> {
    /// Creates a child context that wraps child actions into the parent's action type.
    pub fn map<C: Action + Send + 'static>(&self, wrap: fn(C) -> T) -> ViewContext<'a, C> {
        ViewContext {
            poise: self.poise,
            tx: Arc::new(MappedSender {
                parent_tx: self.tx.clone(),
                wrap,
            }),
        }
    }

    /// Spawns an asynchronous task that can send an action back to the view engine upon completion.
    ///
    /// Useful for performing database or API operations without blocking the interaction response.
    pub fn spawn<F>(&self, future: F)
    where
        F: std::future::Future<Output = Option<T>> + Send + 'static,
    {
        let tx = self.tx.clone();
        tokio::spawn(async move {
            if let Some(action) = future.await {
                tx.send(ViewEvent::Async(action));
            }
        });
    }
}

/// Trait for defining the visual state of a view.
pub trait ViewRender<T: Action> {
    /// Renders the current state into message components or an embed.
    fn render(&self, registry: &mut ActionRegistry<T>) -> ResponseKind<'_>;

    /// Convenience method to build a complete Poise reply from the render output.
    fn create_reply(&self, registry: &mut ActionRegistry<T>) -> CreateReply<'_> {
        self.render(registry).into()
    }
}

/// Trait for managing state and processing interactions.
#[async_trait::async_trait]
pub trait ViewHandler<T: Action>: Send + Sync {
    /// Handles an action triggered by the user or an async task.
    ///
    /// Returns a [`ViewCommand`] to control the engine (e.g., whether to re-render).
    async fn handle(
        &mut self,
        action: T,
        trigger: Trigger<'_>,
        ctx: &ViewContext<'_, T>,
    ) -> Result<ViewCommand, Error>;

    /// Invoked when the view loop times out.
    async fn on_timeout(&mut self) -> Result<(), Error> {
        Ok(())
    }
}

/// The engine that drives the entire View lifecycle.
///
/// The `ViewEngine` performs the following cycle:
/// 1. Calls `render()` to display the initial UI.
/// 2. Enters a `tokio::select!` loop waiting for Discord interactions or async events.
/// 3. Matches interactions back to [`Action`] variants using the [`ActionRegistry`].
/// 4. Dispatches the action to the [`ViewHandler`].
/// 5. Reacts to the returned [`ViewCommand`] (Render, Exit, etc.).
pub struct ViewEngine<'a, T, H>
where
    T: Action + Send + Sync + 'static,
    H: ViewHandler<T> + ViewRender<T>,
{
    /// Poise command context.
    pub ctx: Context<'a>,
    /// The combined handler and renderer.
    pub handler: H,
    /// Registry for mapping custom IDs to actions.
    pub registry: ActionRegistry<T>,
    /// Inactivity timeout for the interaction collector.
    pub timeout: Duration,
    /// Whether the engine should auto-acknowledge component interactions.
    pub should_acknowledge: bool,
    /// Shared handle to the active message.
    shared_handle: SharedReplyHandle<'a>,
}

impl<'a, T, H> ViewEngine<'a, T, H>
where
    T: Action + Send + Sync + 'static,
    H: ViewHandler<T> + ViewRender<T>,
{
    /// Creates a new `ViewEngine` with the given context, handler, timeout and shared handle.
    pub fn new(
        ctx: Context<'a>,
        handler: H,
        timeout: Duration,
        shared_handle: SharedReplyHandle<'a>,
    ) -> Self {
        Self {
            ctx,
            handler,
            registry: ActionRegistry::new(),
            timeout,
            should_acknowledge: true,
            shared_handle,
        }
    }

    /// Sets whether the engine should auto-acknowledge interactions.
    ///
    /// Defaults to `true`. Set to `false` if the handler manual handles the interaction response
    /// (e.g., when opening a modal).
    pub fn acknowledge(mut self, should_acknowledge: bool) -> Self {
        self.should_acknowledge = should_acknowledge;
        self
    }

    /// Triggers a re-render of the UI and edits the current message.
    pub async fn render_view(&mut self) -> Result<(), Error> {
        self.registry.clear();
        let reply = self.handler.create_reply(&mut self.registry);

        let handle_to_edit = {
            let lock = self.shared_handle.lock().await;
            lock.as_ref().cloned()
        };

        if let Some(handle) = handle_to_edit {
            handle.edit(self.ctx, reply).await?;
        } else {
            let handle = self.ctx.send(reply).await?;
            let mut lock = self.shared_handle.lock().await;
            *lock = Some(handle);
        }
        Ok(())
    }

    /// Starts the interactive event loop.
    ///
    /// `on_action` is a callback invoked after every successful action processing,
    /// allowing for external state observation or manual loop control.
    pub async fn run<F>(&mut self, mut on_action: F) -> Result<(), Error>
    where
        F: FnMut(T) -> BoxFuture<'a, ViewCommand> + Send + Sync,
    {
        self.render_view().await?;

        let (tx, mut rx) = mpsc::unbounded_channel::<ViewEvent<T>>();

        let msg_id = {
            let lock = self.shared_handle.lock().await;
            lock.as_ref()
                .cloned()
                .expect("ReplyHandle should be present after render_view")
                .message()
                .await?
                .id
        };

        let collector = ComponentInteractionCollector::new(self.ctx.serenity_context())
            .author_id(self.ctx.author().id)
            .message_id(msg_id)
            .timeout(self.timeout);

        let mut stream = collector.stream();

        let ctx_wrapper = ViewContext {
            poise: self.ctx,
            tx: Arc::new(tx.clone()),
        };

        loop {
            tokio::select! {
                interaction = stream.next() => {
                    let interaction = match interaction {
                        Some(i) => i,
                        None => {
                            let _ = tx.send(ViewEvent::Timeout);
                            continue;
                        }
                    };

                    if let Some(action) = self.registry.get(&interaction.data.custom_id).cloned() {
                        let cmd = self.handler.handle(action.clone(), Trigger::Component(&interaction), &ctx_wrapper).await?;
                        debug!("Handle returned {:?}", cmd);

                        if self.should_acknowledge && !matches!(cmd, ViewCommand::AlreadyResponded) {
                            interaction.create_response(
                                self.ctx.http(),
                                CreateInteractionResponse::Acknowledge,
                            ).await.ok();
                        }

                        if let ViewCommand::Render = cmd {
                            self.render_view().await?;
                        } else if let ViewCommand::Exit = cmd {
                            break;
                        }

                        let callback_cmd = on_action(action).await;
                        if let ViewCommand::Render = callback_cmd {
                            self.render_view().await?;
                        } else if let ViewCommand::Exit = callback_cmd {
                            break;
                        }
                    } else if self.should_acknowledge {
                        interaction.create_response(
                            self.ctx.http(),
                            CreateInteractionResponse::Acknowledge,
                        ).await.ok();
                    }
                }

                async_action = rx.recv() => {
                    let event = match async_action {
                        Some(e) => e,
                        None => break,
                    };

                    let mut action_taken = None;

                    let cmd = match event {
                        ViewEvent::Component(action, interaction) => {
                            action_taken = Some(action.clone());
                            self.handler.handle(action, Trigger::Component(&interaction), &ctx_wrapper).await?
                        }
                        ViewEvent::Modal(action, interaction) => {
                            action_taken = Some(action.clone());
                            self.handler.handle(action, Trigger::Modal(&interaction), &ctx_wrapper).await?
                        }
                        ViewEvent::Message(action, msg) => {
                            action_taken = Some(action.clone());
                            self.handler.handle(action, Trigger::Message(&msg), &ctx_wrapper).await?
                        }
                        ViewEvent::Async(action) => {
                            action_taken = Some(action.clone());
                            self.handler.handle(action, Trigger::Async, &ctx_wrapper).await?
                        }
                        ViewEvent::Timeout => {
                            self.handler.on_timeout().await?;
                            ViewCommand::Render
                        }
                    };

                    if let ViewCommand::Render = cmd {
                        self.render_view().await?;
                    } else if let ViewCommand::Exit = cmd {
                        break;
                    }

                    if let Some(action) = action_taken {
                        let callback_cmd = on_action(action).await;
                        if let ViewCommand::Render = callback_cmd {
                            self.render_view().await?;
                        } else if let ViewCommand::Exit = callback_cmd {
                            break;
                        }
                    }
                }
            }
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Debug, PartialEq, Clone)]
    enum TestAction {
        First,
        Second,
        #[allow(dead_code)]
        Third,
    }

    impl Action for TestAction {
        fn label(&self) -> &'static str {
            match self {
                TestAction::First => "First",
                TestAction::Second => "Second",
                TestAction::Third => "Third",
            }
        }
    }

    #[test]
    fn test_action_registry_new() {
        let registry = ActionRegistry::<TestAction>::new();
        assert!(registry.actions.is_empty());
    }

    #[test]
    fn test_action_registry_register() {
        let mut registry = ActionRegistry::<TestAction>::new();

        let id1 = registry.register(TestAction::First);
        assert!(id1.label.starts_with("TestAction:"));

        let id2 = registry.register(TestAction::Second);
        assert_ne!(id1, id2);
    }
}
