// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `bot_meta` table.
    ///
    /// (Automatically generated by Diesel.)
    bot_meta (key) {
        /// The `key` column of the `bot_meta` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key -> Text,
        /// The `value` column of the `bot_meta` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `feed_items` table.
    ///
    /// (Automatically generated by Diesel.)
    feed_items (id) {
        /// The `id` column of the `feed_items` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `feed_id` column of the `feed_items` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        feed_id -> Int4,
        /// The `description` column of the `feed_items` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
        /// The `published` column of the `feed_items` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        published -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `feed_subscriptions` table.
    ///
    /// (Automatically generated by Diesel.)
    feed_subscriptions (id) {
        /// The `id` column of the `feed_subscriptions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `feed_id` column of the `feed_subscriptions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        feed_id -> Int4,
        /// The `subscriber_id` column of the `feed_subscriptions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        subscriber_id -> Int4,
    }
}

diesel::table! {
    /// Representation of the `feeds` table.
    ///
    /// (Automatically generated by Diesel.)
    feeds (id) {
        /// The `id` column of the `feeds` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `name` column of the `feeds` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `description` column of the `feeds` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
        /// The `platform_id` column of the `feeds` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        platform_id -> Text,
        /// The `source_id` column of the `feeds` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        source_id -> Text,
        /// The `items_id` column of the `feeds` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        items_id -> Text,
        /// The `source_url` column of the `feeds` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        source_url -> Text,
        /// The `cover_url` column of the `feeds` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        cover_url -> Text,
        /// The `tags` column of the `feeds` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        tags -> Text,
    }
}

diesel::table! {
    /// Representation of the `server_settings` table.
    ///
    /// (Automatically generated by Diesel.)
    server_settings (guild_id) {
        /// The `guild_id` column of the `server_settings` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guild_id -> Int8,
        /// The `settings` column of the `server_settings` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        settings -> Jsonb,
    }
}

diesel::table! {
    /// Representation of the `subscribers` table.
    ///
    /// (Automatically generated by Diesel.)
    subscribers (id) {
        /// The `id` column of the `subscribers` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `type` column of the `subscribers` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        #[sql_name = "type"]
        type_ -> Text,
        /// The `target_id` column of the `subscribers` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        target_id -> Text,
    }
}

diesel::table! {
    /// Representation of the `voice_sessions` table.
    ///
    /// (Automatically generated by Diesel.)
    voice_sessions (id) {
        /// The `id` column of the `voice_sessions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `user_id` column of the `voice_sessions` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Int8,
        /// The `guild_id` column of the `voice_sessions` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guild_id -> Int8,
        /// The `channel_id` column of the `voice_sessions` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        channel_id -> Int8,
        /// The `join_time` column of the `voice_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        join_time -> Timestamptz,
        /// The `leave_time` column of the `voice_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        leave_time -> Timestamptz,
        /// The `is_active` column of the `voice_sessions` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_active -> Bool,
    }
}

diesel::joinable!(feed_items -> feeds (feed_id));
diesel::joinable!(feed_subscriptions -> feeds (feed_id));
diesel::joinable!(feed_subscriptions -> subscribers (subscriber_id));

diesel::allow_tables_to_appear_in_same_query!(
    bot_meta,
    feed_items,
    feed_subscriptions,
    feeds,
    server_settings,
    subscribers,
    voice_sessions,
);
