// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `bot_meta` table.
    ///
    /// (Automatically generated by Diesel.)
    bot_meta (key) {
        /// The `key` column of the `bot_meta` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key -> Text,
        /// The `value` column of the `bot_meta` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
    }
}

diesel::table! {
    /// Representation of the `guild_plugins` table.
    ///
    /// (Automatically generated by Diesel.)
    guild_plugins (guild_id, plugin_name) {
        /// The `guild_id` column of the `guild_plugins` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guild_id -> Int8,
        /// The `plugin_name` column of the `guild_plugins` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        plugin_name -> Text,
        /// The `enabled` column of the `guild_plugins` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        enabled -> Bool,
    }
}

diesel::table! {
    /// Representation of the `plugin_kv` table.
    ///
    /// (Automatically generated by Diesel.)
    plugin_kv (namespace, key) {
        /// The `namespace` column of the `plugin_kv` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        namespace -> Text,
        /// The `key` column of the `plugin_kv` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key -> Text,
        /// The `value` column of the `plugin_kv` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Text,
        /// The `updated_at` column of the `plugin_kv` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `server_settings` table.
    ///
    /// (Automatically generated by Diesel.)
    server_settings (guild_id) {
        /// The `guild_id` column of the `server_settings` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guild_id -> Int8,
        /// The `settings` column of the `server_settings` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        settings -> Jsonb,
    }
}

diesel::allow_tables_to_appear_in_same_query!(bot_meta, guild_plugins, plugin_kv, server_settings);
