%% UI Flow
graph TB
    subgraph Views
        subgraph About
            AboutView["AboutView<br/>/about"]
        end

        subgraph Feed
            FeedNavigationView
            FeedSubscribeView
            FeedUnsubscribeView

            FeedSubscriptionBatchView["FeedSubscriptionBatchView<br/>/feed subscribe<br/>/feed unsubscribe"]
            FeedSubscriptionListView["FeedSubscriptionListView<br/>/feed subscriptions"]
        end

        subgraph Voice
            VoiceLeaderboardView["VoiceLeaderboardView<br/>/vc leaderboard"]
        end

        subgraph Settings
            SettingsMainView["SettingsMainView<br/>/settings"]
            SettingsFeedView["SettingsFeedView<br/>/feed settings"]
            SettingsVoiceView["SettingsVoiceView<br/>/vc settings"]
            SettingsNavigationView
        end

        PaginationView
    end

    %% View relationships
    FeedSubscriptionListView -.uses.-> PaginationView
    VoiceLeaderboardView -.uses.-> PaginationView

    SettingsNavigationView <-->|navigates| SettingsMainView
    SettingsNavigationView <-->|navigates| SettingsFeedView
    SettingsNavigationView <-->|navigates| SettingsVoiceView

    FeedNavigationView <-->|navigates| FeedSubscribeView
    FeedNavigationView <-->|navigates| FeedUnsubscribeView
    FeedNavigationView <-->|navigates| FeedSubscriptionListView
    FeedNavigationView <-->|navigates| FeedSubscriptionBatchView
